# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               BBoldt
tagline:             'BBoldt Stuff'
description:         'BBoldt Description'
url:                 http://lanyon.getpoole.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              BBoldt
  url:               https://twitter.com/BBoldt92
  email:             bboldt92@yahoo.com

# Custom vars
version:             1.0.0
